/*
 * This file was automatically generated by EvoSuite
 * Thu Mar 13 21:00:11 GMT 2025
 */

package maven;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import maven.Money;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Money_ESTest extends Money_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Money money0 = new Money(2097, "A(r$ik");
      Money money1 = money0.add(money0);
      boolean boolean0 = money0.equals(money1);
      assertFalse(boolean0);
      assertFalse(money1.equals((Object)money0));
      assertEquals(4194, money1.getAmount());
      assertEquals(2097, money0.getAmount());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Money money0 = new Money((-1), "maven.Money");
      money0.getCurrency();
      assertEquals((-1), money0.getAmount());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Money money0 = new Money(0, "");
      money0.getCurrency();
      assertEquals(0, money0.getAmount());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Money money0 = new Money(0, "");
      int int0 = money0.getAmount();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Money money0 = new Money(1, "$7");
      int int0 = money0.getAmount();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Money money0 = new Money(0, "");
      Money money1 = money0.add(money0);
      assertEquals(0, money1.getAmount());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Money money0 = new Money((-1), "GGg/_aA[Z3R:HQKMc");
      // Undeclared exception!
      try { 
        money0.add((Money) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("maven.Money", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Money money0 = new Money((-1426), (String) null);
      money0.getCurrency();
      assertEquals((-1426), money0.getAmount());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Money money0 = new Money((-3746), "ZySe-Q%_X!MXr%");
      boolean boolean0 = money0.equals(money0);
      assertEquals((-3746), money0.getAmount());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Money money0 = new Money(1267, "ZySe-Q%z_X!LXq%");
      Money money1 = new Money(1267, "ZySe-Q%z_X!MXq%");
      boolean boolean0 = money1.equals(money0);
      assertFalse(boolean0);
      assertEquals(1267, money1.getAmount());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Money money0 = new Money((-3746), "ZySe-Q%_X!MXr%");
      Money money1 = money0.add(money0);
      boolean boolean0 = money0.equals(money1);
      assertEquals((-7492), money1.getAmount());
      assertFalse(boolean0);
      assertFalse(money1.equals((Object)money0));
      assertEquals((-3746), money0.getAmount());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Money money0 = new Money((-3746), "ZySe-Q%_X!MXr%");
      boolean boolean0 = money0.equals("ZySe-Q%_X!MXr%");
      assertEquals((-3746), money0.getAmount());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Money money0 = new Money((-1426), (String) null);
      // Undeclared exception!
      try { 
        money0.equals(money0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Money money0 = new Money((-1426), (String) null);
      int int0 = money0.getAmount();
      assertEquals((-1426), int0);
  }
}
